package com.appsng.greendaoapp.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "PRODUCT".
 */
@Entity
public class product {

    @Id(autoincrement = true)
    private Long id;
    private int product_id;
    private String name;
    private String price;
    private String count;
    private String code;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public product() {
    }

    public product(Long id) {
        this.id = id;
    }

    @Generated
    public product(Long id, int product_id, String name, String price, String count, String code) {
        this.id = id;
        this.product_id = product_id;
        this.name = name;
        this.price = price;
        this.count = count;
        this.code = code;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getProduct_id() {
        return product_id;
    }

    public void setProduct_id(int product_id) {
        this.product_id = product_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public String getCount() {
        return count;
    }

    public void setCount(String count) {
        this.count = count;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
